export const SET_LOADING = "SET_LOADING"
export const SET_USER_DATA = "SET_USER_DATA"
export const CLEAR_USER_DATA = "CLEAR_USER_DATA"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const SET_ERROR_TYPE = "SET_ERROR_TYPE"
export const CLEAR_ERROR_TYPE = "CLEAR_ERROR_TYPE"
